version: '3.5'

services:

        backend:
            image: backend-go
            environment:
                POSTGRES_HOST: db_backend
                POSTGRES_USER: postgres
                POSTGRES_PASSWORD: postgres
                POSTGRES_DATABASE: postgres
            ports: 
                - 8080:8080

        frontend:
            image: hello-frontend
            ports: 
                - 5000:5000

        redis:
            image: redis:alpine3.13
            restart: unless-stopped
            ports:
                - 6379:6379
            volumes:
                - ./data:/data
            container_name: redis
        
        db:
            image: postgres:13.2-alpine
            restart: unless-stopped
            environment:
                POSTGRES_PASSWORD: postgres
            volumes:
                - ./database:/var/lib/postgresql/data
            container_name: db_backend

