version: "3.5"

services:
  backend:
    image: ml-backend
    ports:
      - 5000:5000
    volumes:
      - model:/src/model
    container_name: backend

  frontend:
    image: ml-frontend
    ports:
      - 3000:3000
    container_name: frontend

  training:
    image: ml-training
    volumes:
      - imgs:/src/imgs
      - model:/src/model
    container_name: training

volumes:
  model:
  imgs:
