version: '3.5'

services:

        backend:
                image: backend-go
                ports: 
                        - 8080:8080

        frontend:
                image: hello-frontend
                ports: 
                        - 5000:5000

        redis:
                image: redis:alpine3.13
                restart: unless-stopped
                ports:
                        - 6379:6379
                container_name: redis
